spring.application.name=advisingportal

spring.datasource.url=jdbc:mysql://localhost:3306/advising_portal_db
spring.datasource.username=advisinguser
spring.datasource.password=advisingpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.thymeleaf.cache=false

server.forward-headers-strategy=framework